services:
  database:
    image: "postgres:15.7-alpine"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    command:
      - postgres
      - -c
      - fsync=off
      - -c
      - synchronous_commit=off
      - -c
      - full_page_writes=off
      - -c
      - bgwriter_lru_maxpages=0
      - -c
      - random_page_cost=1.0
      - -c
      - log_min_duration_statement=0
      - -c
      - log_statement=all
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "test_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
