CREATE TABLE "da-box_accounts_table" (
	"userId" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"providerAccountId" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "da-box_accounts_table_provider_providerAccountId_pk" PRIMARY KEY("provider","providerAccountId")
);
--> statement-breakpoint
CREATE TABLE "da-box_files_table" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "da-box_files_table_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"size" integer NOT NULL,
	"url" varchar(256) NOT NULL,
	"parent" integer NOT NULL,
	"owner" varchar(255) NOT NULL,
	"modified" timestamp with time zone,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "da-box_folders_table" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "da-box_folders_table_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"parent" integer,
	"owner" varchar(255) NOT NULL,
	"modified" timestamp with time zone,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "da-box_sessions_table" (
	"sessionToken" varchar(255) PRIMARY KEY NOT NULL,
	"userId" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "da-box_users_table" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"emailVerified" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"image" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "da-box_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "da-box_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
ALTER TABLE "da-box_accounts_table" ADD CONSTRAINT "da-box_accounts_table_userId_da-box_users_table_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."da-box_users_table"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "da-box_files_table" ADD CONSTRAINT "da-box_files_table_parent_da-box_folders_table_id_fk" FOREIGN KEY ("parent") REFERENCES "public"."da-box_folders_table"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "da-box_files_table" ADD CONSTRAINT "da-box_files_table_owner_da-box_users_table_id_fk" FOREIGN KEY ("owner") REFERENCES "public"."da-box_users_table"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "da-box_folders_table" ADD CONSTRAINT "da-box_folders_table_owner_da-box_users_table_id_fk" FOREIGN KEY ("owner") REFERENCES "public"."da-box_users_table"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "da-box_folders_table" ADD CONSTRAINT "da-box_folders_table_parent_da-box_folders_table_id_fk" FOREIGN KEY ("parent") REFERENCES "public"."da-box_folders_table"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "da-box_sessions_table" ADD CONSTRAINT "da-box_sessions_table_userId_da-box_users_table_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."da-box_users_table"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "da-box_accounts_table" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "modified_files_idx" ON "da-box_files_table" USING btree ("modified");--> statement-breakpoint
CREATE INDEX "owner_files_idx" ON "da-box_files_table" USING btree ("owner");--> statement-breakpoint
CREATE INDEX "parent_files_idx" ON "da-box_files_table" USING btree ("parent");--> statement-breakpoint
CREATE INDEX "modified_folders_idx" ON "da-box_folders_table" USING btree ("modified");--> statement-breakpoint
CREATE INDEX "owner_folders_idx" ON "da-box_folders_table" USING btree ("owner");--> statement-breakpoint
CREATE INDEX "parent_folders_idx" ON "da-box_folders_table" USING btree ("parent");--> statement-breakpoint
CREATE INDEX "t_user_id_idx" ON "da-box_sessions_table" USING btree ("userId");