import type { FileItem } from "~/lib/interface";

export const mockData: FileItem[] = [
  // Root level items
  {
    id: "1",
    name: "Documents",
    type: "folder",
    modified: "2024-01-15",
    owner: "You",
  },
  {
    id: "2",
    name: "Photos",
    type: "folder",
    modified: "2024-01-14",
    owner: "You",
  },
  {
    id: "3",
    name: "Videos",
    type: "folder",
    modified: "2024-01-13",
    owner: "You",
  },
  {
    id: "4",
    name: "Project Proposal.docx",
    type: "document",
    size: "2.4 MB",
    modified: "2024-01-12",
    owner: "You",
    url: "#",
    starred: true,
  },
  {
    id: "5",
    name: "Budget 2024.xlsx",
    type: "document",
    size: "1.8 MB",
    modified: "2024-01-11",
    owner: "John Doe",
    shared: true,
    url: "#",
  },

  // Documents folder items
  {
    id: "6",
    name: "Resume.pdf",
    type: "document",
    size: "245 KB",
    modified: "2024-01-10",
    owner: "You",
    parentId: "1",
    url: "#",
  },
  {
    id: "7",
    name: "Meeting Notes",
    type: "folder",
    modified: "2024-01-09",
    owner: "You",
    parentId: "1",
  },
  {
    id: "8",
    name: "Contract.docx",
    type: "document",
    size: "1.2 MB",
    modified: "2024-01-08",
    owner: "You",
    parentId: "1",
    url: "#",
  },

  // Photos folder items
  {
    id: "9",
    name: "Vacation 2023",
    type: "folder",
    modified: "2023-12-20",
    owner: "You",
    parentId: "2",
  },
  {
    id: "10",
    name: "Profile Picture.jpg",
    type: "image",
    size: "3.2 MB",
    modified: "2024-01-05",
    owner: "You",
    parentId: "2",
    url: "#",
  },
  {
    id: "11",
    name: "Screenshot.png",
    type: "image",
    size: "1.1 MB",
    modified: "2024-01-04",
    owner: "You",
    parentId: "2",
    url: "#",
  },

  // Videos folder items
  {
    id: "12",
    name: "Presentation Recording.mp4",
    type: "video",
    size: "125 MB",
    modified: "2024-01-03",
    owner: "You",
    parentId: "3",
    url: "#",
  },
  {
    id: "13",
    name: "Tutorial.mov",
    type: "video",
    size: "89 MB",
    modified: "2024-01-02",
    owner: "You",
    parentId: "3",
    url: "#",
  },

  // Meeting Notes folder items
  {
    id: "14",
    name: "Q1 Planning.docx",
    type: "document",
    size: "890 KB",
    modified: "2024-01-01",
    owner: "You",
    parentId: "7",
    url: "#",
  },
  {
    id: "15",
    name: "Team Standup.txt",
    type: "document",
    size: "12 KB",
    modified: "2023-12-30",
    owner: "You",
    parentId: "7",
    url: "#",
  },
  // Additional root level items
  {
    id: "16",
    name: "Music Collection",
    type: "folder",
    modified: "2024-01-16",
    owner: "You",
  },
  {
    id: "17",
    name: "Archives",
    type: "folder",
    modified: "2024-01-17",
    owner: "You",
  },
  {
    id: "18",
    name: "Presentation.pptx",
    type: "document",
    size: "5.2 MB",
    modified: "2024-01-18",
    owner: "You",
    url: "#",
    starred: true,
  },
  {
    id: "19",
    name: "Backup.zip",
    type: "archive",
    size: "45 MB",
    modified: "2024-01-19",
    owner: "You",
    url: "#",
  },
  {
    id: "20",
    name: "Demo Video.mp4",
    type: "video",
    size: "78 MB",
    modified: "2024-01-20",
    owner: "Jane Smith",
    shared: true,
    url: "#",
  },

  // Music Collection folder items
  {
    id: "21",
    name: "Favorite Songs.mp3",
    type: "audio",
    size: "4.5 MB",
    modified: "2024-01-21",
    owner: "You",
    parentId: "16",
    url: "#",
  },
  {
    id: "22",
    name: "Podcast Episode.mp3",
    type: "audio",
    size: "25 MB",
    modified: "2024-01-22",
    owner: "You",
    parentId: "16",
    url: "#",
  },

  // Archives folder items
  {
    id: "23",
    name: "Old Projects.zip",
    type: "archive",
    size: "120 MB",
    modified: "2024-01-23",
    owner: "You",
    parentId: "17",
    url: "#",
  },
  {
    id: "24",
    name: "Photos Backup.rar",
    type: "archive",
    size: "89 MB",
    modified: "2024-01-24",
    owner: "You",
    parentId: "17",
    url: "#",
  },

  // Vacation 2023 folder items
  {
    id: "25",
    name: "Beach Photos.jpg",
    type: "image",
    size: "2.8 MB",
    modified: "2023-12-19",
    owner: "You",
    parentId: "9",
    url: "#",
  },
  {
    id: "26",
    name: "Mountain View.png",
    type: "image",
    size: "4.1 MB",
    modified: "2023-12-18",
    owner: "You",
    parentId: "9",
    url: "#",
  },
];
