import "~/styles/globals.css";

import type { Metadata } from "next";
import { Geist } from "next/font/google";
import localFont from "next/font/local";
import { Toaster } from "~/components/ui/sonner";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Da Box - Cloud Storage",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const dela = localFont({
  variable: "--font-dela-gothic-one",
  src: "../../public/fonts/DelaGothicOne-Regular.ttf",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${dela.variable} ${geist.variable}`}>
      <body>
        <Providers>
          <div className="bg-background text-foreground">{children}</div>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
